# Generated by Django 5.0.3 on 2024-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DurationField()),
                ('subject_name', models.CharField(max_length=50)),
                ('exam_name', models.CharField(max_length=50)),
                ('faculty_name', models.CharField(max_length=50)),
                ('have_file', models.BooleanField()),
                ('file_upload', models.FileField(upload_to='', verbose_name='labexam-data/')),
                ('student_files', models.BooleanField()),
                ('student_files_upload', models.FileField(upload_to='', verbose_name='labexam-data/student-uploads/')),
            ],
        ),
    ]
